import { join } from "node:path";
import { logger } from "@type-ninja/core/logger";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { getDB } from "./drizzle";

const MIGRATIONS_FOLDER = join(import.meta.dirname, "migrations");

/** Applies pending SQL migrations from `src/migrations` (generated by drizzle-kit). */
export async function runMigrations() {
	logger.info({ folder: MIGRATIONS_FOLDER }, "running migrations");
	await migrate(getDB(), { migrationsFolder: MIGRATIONS_FOLDER });
	logger.info("migrations complete");
}
